- name: nginx install and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

- name: mysql install and run
  #hosts: web
  #become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql
      state: present
      
  - name: run mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes