- name: nginx install and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

- name: snmp install and run
  hosts: web
  become: yes
  tasks:
  - name: install snmp
    ansible.builtin.package:
      name: snmp
      state: present
      
  - name: run snmp
    ansible.builtin.service:
      name: snmp
      state: started
      enabled: yes