- name: nginx install and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

- name: postfix install and run
  hosts: web
  become: yes
  tasks:
  - name: install postfix
    ansible.builtin.package:
      name: postfix
      state: present
      
  - name: run postfix
    ansible.builtin.service:
      name: postfix
      state: started
      enabled: yes