- name: Variables to print
  hosts: web
  vars: # Play level
    COURSE: "DevOps with AWS"
    DURATION: "140HRS"
    TRAINER: "Siva Kumar"
  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "Hi, I am lerning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: Print the information again
    vars: # Task level
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am lerning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"