- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with aws from PLAY level"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: Please enter the COURSE name
    private: false
  tasks:
 # - name: Print the information
    vars:
   #   COURSE: "DevOps with AWS from Task level"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}"