- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: " Hello {{ course | default('ansible')}}"
  # - name: convert to uppercase
  #   vars:
  #     greeting: "Hello Ramesh"
  #   ansible.builtin.debug:
  #     msg: " {{ greeting | upper }}"